; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:NUVOLA32]
platform = espressif32
board = NUVOLA32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
;board_build.filesystem = spiffs
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram_type = opi
lib_ignore =
    WebServer
lib_deps =
    https://github.com/MAKERSUN99/LovyanGFX.git
    xreef/PCF8574 library
build_flags =   
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DBOARD_HAS_PSRAM
  -DHTTP_PARSER_STRICT=1
  -DCORE_DEBUG_LEVEL=5
  -O3 -fno-tree-loop-distribute-patterns
  -mlongcalls
  -I src/
  -DUSE_CZ80=1
  -DCZ80=1
  -DUSE_SDL=1
  -Ilib/race/
